# permissions for end users to edit dnsnames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsname-editor-role
rules:
- apiGroups:
  - networking.liebler.dev
  resources:
  - dnsnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.liebler.dev
  resources:
  - dnsnames/status
  verbs:
  - get
