---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.liebler.dev
  resources:
  - dnsnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.liebler.dev
  resources:
  - dnsnames/finalizers
  verbs:
  - update
- apiGroups:
  - networking.liebler.dev
  resources:
  - dnsnames/status
  verbs:
  - get
  - patch
  - update
