apiVersion: networking.liebler.dev/v1alpha1
kind: DNSName
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsname-sample-cname
spec:
  type: CNAME
  domain: foobar.de
  target: homelab
  ttl: 300
---
# IPv4 example
apiVersion: networking.liebler.dev/v1alpha1
kind: DNSName
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsname-sample-a
spec:
  type: A
  domain: foobar.com
  targetIP: 192.168.178.1
---
# IPv6 example
apiVersion: networking.liebler.dev/v1alpha1
kind: DNSName
metadata:
  labels:
    app.kubernetes.io/name: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsname-sample-a
spec:
  type: A
  domain: foobar.com
  targetIP: 2001:db8::1
